### ISSUE TITLE
Make the staging site private

### ISSUE THREAD

**Issue by EFT-Defra** [Defra-Data-Science-Centre-of-Excellence/OIF-Pipeline-Orchestration#16]
The stats team need the staging dashboard to be private as some of the data in the upcoming release will only be published when it is.

Todo:
- [x] Make Data repo private
- [x] Make Site repo private
- [x] Unpublish GitHub pages
- [ ] Remove Deploy to staging GitHub Actions workflow
- [ ] Find an alternative way to host the built site privately
