### ISSUE TITLE
Provision compute for executing Notebooks with pipeline code

### ISSUE THREAD

**Issue by EFT-Defra** [Defra-Data-Science-Centre-of-Excellence/OIF-Pipeline-Orchestration#5]
I already have:
- [x] A Linux VM (w/ sudo privileges and SSH access)
- [x] A URL that's accessible from with the Defra network
- [x] An Nginx reverse proxy 

But I need to:
- [x] Install JupyterHub
- [x] Configure the reverse proxy
- [ ] Upgrade the connection to HTTPS

**Comment by EFT-Defra** [comment]
@TimAshelford, I'll keep this in review until we've had a chance to discuss but @Jtsmith275 has confirmed that he can run the notebook containing the oiflib code, so it looks like we have a working solution. I've got an outstanding ticket with the SCE support team about upgrading to HTTPS but that isn't essential for this to work as we're already within the Defra network.
